/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AccountStatusEnum = "ACTIVE" | "CLOSED" | "SUSPENDED";

export type ActorTypeEnum = "ADMIN" | "GUEST" | "SYSTEM" | "USER";

export type AuthAttemptResultEnum = "FAILED_LOCKED" | "FAILED_PASSWORD" | "FAILED_UNKNOWN" | "RATE_LIMITED" | "SUCCESS";

export type AwardStatusEnum = "ACTIVE" | "SUPERSEDED" | "VOID";

export type AwardTypeEnum = "CASH" | "FREE_TICKET" | "MIXED";

export type CalcRunStatusEnum = "APPROVED" | "COMPLETED" | "FAILED" | "PUBLISHED" | "RUNNING" | "SUPERSEDED";

export type ClaimantTypeEnum = "GUEST" | "USER";

export type ClaimAwardLinkReasonEnum = "INITIAL_CLAIM" | "RESULT_CORRECTION";

export type ClaimStatusEnum = "APPROVED" | "DISPUTED" | "EXPIRED" | "FROZEN" | "NEEDS_INFO" | "PAID" | "PAYMENT_PENDING" | "PENDING_REVIEW" | "READY_FOR_PAYMENT" | "REJECTED" | "SUPERSEDED";

export type ClaimSubmissionMethodEnum = "ACCOUNT" | "ADMIN_ASSISTED" | "CLAIM_TOKEN";

export type CredentialReasonEnum = "INITIAL" | "RECOVERY";

export type CredentialStatusEnum = "ACTIVE" | "REVOKED" | "ROTATED" | "USED";

export type DrawEvidenceStatusEnum = "ENDED" | "LIVE" | "SCHEDULED" | "UNAVAILABLE";

export type DrawStatusEnum = "CANCELLED" | "CLOSED" | "DELAYED" | "DRAW_IN_PROGRESS" | "PENDING_REVIEW" | "PUBLISHED" | "RESULT_ENTERED" | "SALES_CLOSED" | "SALES_OPEN" | "SETTLED" | "VOID";

export type GameStatusEnum = "ACTIVE" | "ARCHIVED" | "PAUSED";

export type GameTypeEnum = "FOUR_LEAF" | "SIX_CHANCE";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type NotificationChannelEnum = "EMAIL" | "IN_APP";

export type NotificationStatusEnum = "DELIVERED" | "FAILED" | "QUEUED" | "SENDING";

export type OrderStatusEnum = "CANCELLED" | "CONFIRMED" | "DRAFT" | "EXPIRED" | "PENDING_PAYMENT" | "REFUNDED";

export type OutboxStatusEnum = "FAILED" | "PENDING" | "PROCESSED" | "PROCESSING";

export type OverrideScopeEnum = "ENTIRE_DRAW" | "FUTURE_DRAWS" | "NEW_PURCHASES" | "SPECIFIC_RECORD";

export type OwnershipChangeTypeEnum = "ATTACH" | "DETACH" | "REASSIGN";

export type PermissionRiskEnum = "CRITICAL" | "SENSITIVE" | "STANDARD";

export type PurchaserTypeEnum = "GUEST" | "USER";

export type RecipientTypeEnum = "ADMIN" | "GUEST" | "USER";

export type RequesterTypeEnum = "GUEST" | "USER";

export type ResultStatusEnum = "ENTERED" | "PENDING_REVIEW" | "PUBLISHED" | "SUPERSEDED" | "VOID";

export type RuleVersionStatusEnum = "ACTIVE" | "DRAFT" | "RETIRED";

export type SessionPrincipalEnum = "ADMIN" | "USER";

export type SessionStatusEnum = "ACTIVE" | "EXPIRED" | "REVOKED";

export type SupportCategoryEnum = "ACCOUNT_ATTACHMENT" | "ACCOUNT_PROBLEM" | "CLAIM_PROBLEM" | "LOST_CLAIM_TOKEN" | "MISSING_TICKET" | "PAYMENT_PROBLEM" | "RESULT_OR_PRIZE_DISPUTE";

export type SupportStatusEnum = "CLOSED" | "OPEN" | "PENDING_CUSTOMER" | "PENDING_INTERNAL" | "RESOLVED";

export type TicketOutcomeEnum = "NOT_WINNER" | "PENDING" | "VOID" | "WINNER";

export type TicketSourceEnum = "FREE_PRIZE" | "PURCHASE";

export type TicketStatusEnum = "CANCELLED" | "CONFIRMED" | "PENDING" | "REFUNDED" | "VOID";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AdminAccounts {
  admin_number: string;
  auth_version: Generated<number>;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  status: Generated<AccountStatusEnum>;
  updated_at: Generated<Timestamp>;
}

export interface AdminCredentials {
  admin_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  password_hash: string;
  password_updated_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface AdminOverrides {
  action_type: string;
  admin_id: string;
  after_snapshot: Json;
  before_snapshot: Json;
  board_decision_reference: string | null;
  confirmation_method: string;
  created_at: Generated<Timestamp>;
  effective_at: Timestamp;
  entity_id: string;
  entity_type: string;
  id: Generated<string>;
  impact_snapshot: Json;
  reason: string;
  request_id: string;
  scope: OverrideScopeEnum;
}

export interface AdminRoleAssignments {
  admin_id: string;
  assigned_at: Generated<Timestamp>;
  assigned_by: string | null;
  id: Generated<string>;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  role_id: string;
}

export interface AuditLogs {
  action: string;
  actor_admin_id: string | null;
  actor_type: ActorTypeEnum;
  actor_user_id: string | null;
  changed_fields: string[] | null;
  created_at: Generated<Timestamp>;
  entity_id: string;
  /**
   * Deliberate unenforced polymorphic reference alongside entity_id (documented referential-integrity exception): an audited entity can be any business record.
   */
  entity_type: string;
  evidence: Json | null;
  /**
   * Hash of a guest-identifying value (e.g. email); never the raw value.
   */
  guest_identifier_hash: Buffer | null;
  id: Generated<string>;
  ip_address: string | null;
  new_values: Json | null;
  old_values: Json | null;
  reason: string | null;
  request_id: string | null;
  severity: Generated<string>;
  user_agent: string | null;
}

export interface AuthAttempts {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  identifier_hash: Buffer;
  ip_address: string | null;
  principal_type: SessionPrincipalEnum;
  result: AuthAttemptResultEnum;
  user_agent: string | null;
}

export interface ClaimCredentials {
  created_at: Generated<Timestamp>;
  created_reason: Generated<CredentialReasonEnum>;
  id: Generated<string>;
  replaces_credential_id: string | null;
  revocation_reason: string | null;
  revoked_at: Timestamp | null;
  rotated_at: Timestamp | null;
  status: Generated<CredentialStatusEnum>;
  ticket_id: string;
  /**
   * SHA-256 digest of the raw Claim Token. Lookup hashes the submitted token then queries this unique index.
   */
  token_digest: Buffer;
  used_at: Timestamp | null;
}

export interface DrawEvidence {
  archive_url: string | null;
  created_at: Generated<Timestamp>;
  draw_id: string;
  ended_at: Timestamp | null;
  evidence_hash: Buffer | null;
  id: Generated<string>;
  scheduled_at: Timestamp | null;
  started_at: Timestamp | null;
  status: Generated<DrawEvidenceStatusEnum>;
  updated_at: Generated<Timestamp>;
  youtube_live_url: string;
  youtube_video_id: string;
}

export interface Draws {
  created_at: Generated<Timestamp>;
  /**
   * Rule version applied to new purchases for this draw; independent of the game-wide ACTIVE version so a draw can pin its own effective version.
   */
  current_rule_version_id: string;
  current_rules_snapshot: Json;
  draw_at: Timestamp;
  draw_number: Int8;
  final_jackpot_toman: Int8 | null;
  game_id: string;
  game_type: GameTypeEnum;
  id: Generated<string>;
  official_timezone: string;
  opening_jackpot_toman: Int8 | null;
  published_at: Timestamp | null;
  sales_closes_at: Timestamp;
  sales_opens_at: Timestamp;
  schedule_claim: string | null;
  schedule_timezone: string | null;
  scheduled_draw_at: Timestamp | null;
  scheduled_local_date: Timestamp | null;
  scheduled_slot_id: string | null;
  settled_at: Timestamp | null;
  status: Generated<DrawStatusEnum>;
  updated_at: Generated<Timestamp>;
  youtube_live_url: string | null;
}

export interface ScheduledOccurrenceDismissals {
  created_at: Generated<Timestamp>;
  dismissed_by: string;
  game_id: string;
  id: Generated<string>;
  local_date: Timestamp;
  reason: string;
  schedule_timezone: string;
  scheduled_draw_at: Timestamp;
  slot_id: string;
}

export interface DrawStatusHistory {
  actor_admin_id: string | null;
  actor_role_snapshot: string | null;
  actor_type: ActorTypeEnum;
  created_at: Generated<Timestamp>;
  draw_id: string;
  from_status: string | null;
  id: Generated<string>;
  override_id: string | null;
  reason: string | null;
  to_status: string;
}

export interface FourLeafResults {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  number_value: string;
  result_game_type: Generated<GameTypeEnum>;
  result_id: string;
}

export interface FourLeafTicketSelections {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  number_value: string;
  ticket_game_type: Generated<GameTypeEnum>;
  ticket_id: string;
}

export interface GameRuleVersions {
  activated_at: Timestamp | null;
  activated_by: string | null;
  change_reason: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  game_id: string;
  game_type: GameTypeEnum;
  id: Generated<string>;
  retired_at: Timestamp | null;
  /**
   * Includes price, prize tiers, caps, schedule shape, jackpot settings, and (Four Leaf) rounding_unit_toman / remainder_destination.
   */
  rules: Json;
  rules_hash: Buffer;
  status: Generated<RuleVersionStatusEnum>;
  version_number: number;
}

export interface Games {
  code: string;
  created_at: Generated<Timestamp>;
  /**
   * Structural game shape (fixed for this release). Distinct from the mutable branding code/slug.
   */
  game_type: GameTypeEnum;
  id: Generated<string>;
  name_en: string;
  name_fa: string;
  slug: string;
  status: Generated<GameStatusEnum>;
  updated_at: Generated<Timestamp>;
}

export interface Notifications {
  attempt_count: Generated<number>;
  channel: NotificationChannelEnum;
  created_at: Generated<Timestamp>;
  event_type: string;
  id: Generated<string>;
  idempotency_key: string;
  language: Generated<string>;
  last_attempt_at: Timestamp | null;
  payload: Generated<Json>;
  provider_message_id: string | null;
  provider_status: string | null;
  recipient_admin_id: string | null;
  recipient_guest_email: string | null;
  recipient_type: RecipientTypeEnum;
  recipient_user_id: string | null;
  rendered_body: string | null;
  rendered_subject: string | null;
  status: Generated<NotificationStatusEnum>;
  template_key: string;
  template_version: number;
  updated_at: Generated<Timestamp>;
}

export interface Orders {
  confirmed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  discount_toman: Generated<Int8>;
  draw_id: string;
  expires_at: Timestamp | null;
  /**
   * Required under the current guest-purchase default (Production Readiness Dependency: finalize verification/recovery requirements before launch).
   */
  guest_email: string | null;
  id: Generated<string>;
  idempotency_key: string;
  order_number: string;
  purchaser_type: PurchaserTypeEnum;
  purchaser_user_id: string | null;
  status: Generated<OrderStatusEnum>;
  subtotal_toman: Int8;
  total_toman: Int8;
  updated_at: Generated<Timestamp>;
}

export interface OutboxEvents {
  aggregate_id: string;
  aggregate_type: string;
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  event_type: string;
  id: Generated<string>;
  idempotency_key: string;
  last_error: string | null;
  payload: Json;
  processed_at: Timestamp | null;
  status: Generated<OutboxStatusEnum>;
}

export interface Permissions {
  action: string;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  module: string;
  risk_level: Generated<PermissionRiskEnum>;
}

export interface PrizeAwardComponents {
  amount_toman: Int8 | null;
  award_id: string;
  calculation_details: Generated<Json>;
  component_type: AwardTypeEnum;
  created_at: Generated<Timestamp>;
  free_ticket_quantity: number | null;
  id: Generated<string>;
  matched_combinations: number;
  tier_code: string;
}

export interface PrizeAwards {
  amount_toman: Int8 | null;
  award_type: AwardTypeEnum;
  calculation_details: Generated<Json>;
  calculation_run_id: string;
  claim_deadline_at: Timestamp;
  created_at: Generated<Timestamp>;
  draw_id: string;
  free_ticket_quantity: number | null;
  id: Generated<string>;
  is_current: Generated<boolean>;
  result_id: string;
  status: Generated<AwardStatusEnum>;
  supersedes_award_id: string | null;
  ticket_id: string;
  tier_code: string;
}

export interface PrizeCalculationRuns {
  approved_at: Timestamp | null;
  approved_by: string | null;
  calculation_hash: Buffer;
  created_at: Generated<Timestamp>;
  created_by: string;
  draw_id: string;
  id: Generated<string>;
  override_id: string | null;
  result_id: string;
  rule_version_id: string;
  run_number: number;
  status: Generated<CalcRunStatusEnum>;
  summary: Generated<Json>;
}

export interface PrizeClaimAwardLinks {
  award_id: string;
  claim_id: string;
  link_reason: ClaimAwardLinkReasonEnum;
  linked_at: Generated<Timestamp>;
  linked_by_admin_id: string | null;
  linked_by_type: ActorTypeEnum;
  ticket_id: string;
}

export interface PrizeClaims {
  approved_at: Timestamp | null;
  claim_credential_id: string | null;
  claim_number: string;
  claimant_type: ClaimantTypeEnum;
  claimant_user_id: string | null;
  contact_email_snapshot: string | null;
  created_at: Generated<Timestamp>;
  /**
   * Nullable: a result correction may supersede the ticket's entitlement to nothing. A PAID claim whose award is later superseded keeps its PAID history untouched and is flagged for manual reconciliation (see prize_claim_status_history), never automatically reversed.
   */
  current_award_id: string | null;
  decision_reason: string | null;
  id: Generated<string>;
  manual_reconciliation_notes: string | null;
  paid_at: Timestamp | null;
  requires_manual_reconciliation: Generated<boolean>;
  reviewed_at: Timestamp | null;
  status: Generated<ClaimStatusEnum>;
  submission_method: ClaimSubmissionMethodEnum;
  submitted_at: Generated<Timestamp>;
  ticket_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PrizeClaimStatusHistory {
  actor_admin_id: string | null;
  actor_type: ActorTypeEnum;
  actor_user_id: string | null;
  claim_id: string;
  created_at: Generated<Timestamp>;
  from_status: string | null;
  id: Generated<string>;
  reason: string | null;
  to_status: string;
}

export interface Results {
  correction_reason: string | null;
  created_at: Generated<Timestamp>;
  draw_evidence_id: string | null;
  draw_id: string;
  entered_at: Generated<Timestamp>;
  /**
   * The first release does not require two different administrators; the same SUPER_ADMIN may enter, review, and publish.
   */
  entered_by: string;
  game_type: GameTypeEnum;
  id: Generated<string>;
  is_public_current: Generated<boolean>;
  publication_reason: string | null;
  published_at: Timestamp | null;
  published_by: string | null;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  status: Generated<ResultStatusEnum>;
  updated_at: Generated<Timestamp>;
  version_number: number;
}

export interface RolePermissions {
  created_at: Generated<Timestamp>;
  permission_id: string;
  role_id: string;
}

export interface Roles {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  /**
   * System-defined roles (ADMIN, SUPER_ADMIN) cannot be deleted through the admin panel.
   */
  is_system: Generated<boolean>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Sessions {
  absolute_expires_at: Timestamp;
  admin_id: string | null;
  /**
   * Snapshot of users.auth_version/admin_accounts.auth_version at issue time; a mismatch means the session is stale after a forced global logout.
   */
  auth_version_at_issue: number;
  created_at: Generated<Timestamp>;
  device_hash: Buffer | null;
  id: Generated<string>;
  idle_expires_at: Timestamp;
  ip_address: string | null;
  principal_type: SessionPrincipalEnum;
  revoked_at: Timestamp | null;
  status: Generated<SessionStatusEnum>;
  token_digest: Buffer;
  user_agent: string | null;
  user_id: string | null;
}

export interface SixChanceResults {
  created_at: Generated<Timestamp>;
  draw_order_values: number[];
  id: Generated<string>;
  normalized_n1: number;
  normalized_n2: number;
  normalized_n3: number;
  normalized_n4: number;
  normalized_n5: number;
  normalized_n6: number;
  result_game_type: Generated<GameTypeEnum>;
  result_id: string;
  symbol: number;
}

export interface SixChanceSystemTicketSelections {
  combination_count: number;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  numbers: number[];
  symbols: number[];
  ticket_game_type: Generated<GameTypeEnum>;
  ticket_id: string;
}

export interface SixChanceTicketSelections {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  n1: number;
  n2: number;
  n3: number;
  n4: number;
  n5: number;
  n6: number;
  symbol: number;
  ticket_game_type: Generated<GameTypeEnum>;
  ticket_id: string;
}

export interface SupportMessages {
  body: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_internal_note: Generated<boolean>;
  sender_admin_id: string | null;
  sender_type: ActorTypeEnum;
  sender_user_id: string | null;
  support_ticket_id: string;
}

export interface SupportTickets {
  assigned_admin_id: string | null;
  case_number: string;
  category: SupportCategoryEnum;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  related_entity_id: string | null;
  related_entity_type: string | null;
  requester_guest_email: string | null;
  requester_type: RequesterTypeEnum;
  requester_user_id: string | null;
  status: Generated<SupportStatusEnum>;
  updated_at: Generated<Timestamp>;
}

export interface TicketOwnershipHistory {
  actor_admin_id: string | null;
  actor_type: ActorTypeEnum;
  actor_user_id: string | null;
  change_type: OwnershipChangeTypeEnum;
  created_at: Generated<Timestamp>;
  from_user_id: string | null;
  id: Generated<string>;
  reason: string | null;
  request_id: string;
  ticket_id: string;
  to_user_id: string | null;
}

export interface Tickets {
  /**
   * Number of (6 numbers, 1 symbol) combinations this line covers: 1 for Four Leaf and exact Six Chance picks; C(n,6)×symbols for a Six Chance system line.
   */
  combination_count: Generated<number>;
  created_at: Generated<Timestamp>;
  draw_id: string;
  game_type: GameTypeEnum;
  id: Generated<string>;
  is_quick_pick: Generated<boolean>;
  line_number: number;
  /**
   * Generated: unit_price_toman × combination_count — the amount this line contributes to its order.
   */
  line_total_toman: Generated<Int8 | null>;
  order_id: string;
  outcome_status: Generated<TicketOutcomeEnum>;
  /**
   * Nullable until a guest ticket is attached to an account. The full attach/reassign/detach history lives in ticket_ownership_history; this column is only the current projection.
   */
  owner_user_id: string | null;
  public_code: string;
  rule_version_id: string;
  source: Generated<TicketSourceEnum>;
  status: Generated<TicketStatusEnum>;
  /**
   * Price of ONE combination, snapshotted from the draw's rule version at purchase time.
   */
  unit_price_toman: Int8;
  updated_at: Generated<Timestamp>;
}

export interface UserCredentials {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  /**
   * Argon2id encoded hash string, not a raw password.
   */
  password_hash: string;
  password_updated_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Users {
  /**
   * Incremented to force global logout of all sessions for this user.
   */
  auth_version: Generated<number>;
  created_at: Generated<Timestamp>;
  email: string;
  email_verified_at: Timestamp | null;
  id: Generated<string>;
  status: Generated<AccountStatusEnum>;
  updated_at: Generated<Timestamp>;
  user_number: string;
}

export interface DB {
  admin_accounts: AdminAccounts;
  admin_credentials: AdminCredentials;
  admin_overrides: AdminOverrides;
  admin_role_assignments: AdminRoleAssignments;
  audit_logs: AuditLogs;
  auth_attempts: AuthAttempts;
  claim_credentials: ClaimCredentials;
  draw_evidence: DrawEvidence;
  draw_status_history: DrawStatusHistory;
  draws: Draws;
  four_leaf_results: FourLeafResults;
  four_leaf_ticket_selections: FourLeafTicketSelections;
  game_rule_versions: GameRuleVersions;
  games: Games;
  notifications: Notifications;
  orders: Orders;
  outbox_events: OutboxEvents;
  permissions: Permissions;
  prize_award_components: PrizeAwardComponents;
  prize_awards: PrizeAwards;
  prize_calculation_runs: PrizeCalculationRuns;
  prize_claim_award_links: PrizeClaimAwardLinks;
  prize_claim_status_history: PrizeClaimStatusHistory;
  prize_claims: PrizeClaims;
  results: Results;
  role_permissions: RolePermissions;
  roles: Roles;
  scheduled_occurrence_dismissals: ScheduledOccurrenceDismissals;
  sessions: Sessions;
  six_chance_results: SixChanceResults;
  six_chance_system_ticket_selections: SixChanceSystemTicketSelections;
  six_chance_ticket_selections: SixChanceTicketSelections;
  support_messages: SupportMessages;
  support_tickets: SupportTickets;
  ticket_ownership_history: TicketOwnershipHistory;
  tickets: Tickets;
  user_credentials: UserCredentials;
  users: Users;
}
